sudo: require

install:
  # LyX
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq
  - sudo apt-get install lyx

script:
  - lyx --export pdflatex travis_lyx_to_tex.lyx
  - if [ ! -e travis_lyx_to_tex.tex ]; then exit 1; fi